import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>

      <style jsx>
        {`
        h2{
          font-size:38px;
        }
        h3{
          font-size:28px;
        }
        `}
      </style>


      <Head>
        <title className=''>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hunting Coder
        </h1>

        <div className="imageWrap">
          <Image className={styles.myImg} src={'/homeimage.avif'} width={237} height={158} alt='Coding Image' />
        </div>


        <p className={styles.description}>
          A blog for hunting coders by the hunting coder.
        </p>

        <div className="blogs">
          <h2>Latest  Blogs</h2>
          <div className="blog">
            <h3>How to learn JavaScript in 2022</h3>
            <p>Javascript is the language usedd to design logic for the web</p>
          </div>
          <div className="blog">
            <h3>How to learn JavaScript in 2022</h3>
            <p>Javascript is the language usedd to design logic for the web</p>
          </div>
          <div className="blog">
            <h3>How to learn JavaScript in 2022</h3>
            <p>Javascript is the language usedd to design logic for the web</p>
          </div>
          <div className="blog">
            <h3>How to learn JavaScript in 2022</h3>
            <p>Javascript is the language usedd to design logic for the web</p>
          </div>
          <div className="blog">
            <h3>How to learn JavaScript in 2022</h3>
            <p>Javascript is the language usedd to design logic for the web</p>
          </div>
        </div>



      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
